// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: availability.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertAvailabilityLog = `-- name: UpsertAvailabilityLog :exec
INSERT INTO coffee_availability_log (coffee_id, in_stock, price_cents, recorded_at)
VALUES ($1, $2, $3, CURRENT_DATE)
ON CONFLICT (coffee_id, recorded_at) DO UPDATE SET
    in_stock = EXCLUDED.in_stock,
    price_cents = EXCLUDED.price_cents
`

type UpsertAvailabilityLogParams struct {
	CoffeeID   int64       `json:"coffee_id"`
	InStock    bool        `json:"in_stock"`
	PriceCents pgtype.Int4 `json:"price_cents"`
}

func (q *Queries) UpsertAvailabilityLog(ctx context.Context, arg UpsertAvailabilityLogParams) error {
	_, err := q.db.Exec(ctx, upsertAvailabilityLog, arg.CoffeeID, arg.InStock, arg.PriceCents)
	return err
}

const listAvailabilityHistory = `-- name: ListAvailabilityHistory :many
SELECT coffee_id, in_stock, price_cents, recorded_at
FROM coffee_availability_log
WHERE coffee_id = $1
ORDER BY recorded_at DESC
LIMIT $2
`

type ListAvailabilityHistoryRow struct {
	CoffeeID   int64       `json:"coffee_id"`
	InStock    bool        `json:"in_stock"`
	PriceCents pgtype.Int4 `json:"price_cents"`
	RecordedAt time.Time   `json:"recorded_at"`
}

func (q *Queries) ListAvailabilityHistory(ctx context.Context, coffeeID int64, limit int32) ([]ListAvailabilityHistoryRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityHistory, coffeeID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailabilityHistoryRow{}
	for rows.Next() {
		var i ListAvailabilityHistoryRow
		if err := rows.Scan(&i.CoffeeID, &i.InStock, &i.PriceCents, &i.RecordedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleCoffeesOutOfStock = `-- name: MarkStaleCoffeesOutOfStock :exec
UPDATE coffees
SET in_stock = false, updated_at = now()
WHERE in_stock = true
  AND last_seen_at < now() - interval '3 days'
`

func (q *Queries) MarkStaleCoffeesOutOfStock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markStaleCoffeesOutOfStock)
	return err
}

const listCoffeesByRoasterWithAvailability = `-- name: ListCoffeesByRoasterWithAvailability :many
SELECT
    c.id, c.roaster_id, c.name, c.product_url, c.image_url,
    c.country_code, c.origin_raw, c.region_raw, c.process, c.roast_level,
    c.tasting_notes, c.price_cents, c.weight_grams, c.in_stock,
    c.variety, c.species,
    c.price_per_100g_min, c.price_per_100g_max, c.is_blend, c.is_decaf,
    r.name AS roaster_name, r.slug AS roaster_slug, r.logo_url AS roaster_logo_url,
    co.name AS country_name,
    reg.name AS region_name, reg.id AS coffee_region_id,
    p.name AS producer_name, p.id AS coffee_producer_id
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN countries co ON co.code = c.country_code
LEFT JOIN regions reg ON reg.id = c.region_id
LEFT JOIN producers p ON p.id = c.producer_id
WHERE r.slug = $1 AND r.opted_out = false
ORDER BY c.in_stock DESC, c.name
`

// ListCoffeesByRoasterWithAvailabilityRow is the same shape as ListCoffeesByRoasterRow.
type ListCoffeesByRoasterWithAvailabilityRow struct {
	ID              int64       `json:"id"`
	RoasterID       int32       `json:"roaster_id"`
	Name            string      `json:"name"`
	ProductUrl      pgtype.Text `json:"product_url"`
	ImageUrl        pgtype.Text `json:"image_url"`
	CountryCode     pgtype.Text `json:"country_code"`
	OriginRaw       pgtype.Text `json:"origin_raw"`
	RegionRaw       pgtype.Text `json:"region_raw"`
	Process         pgtype.Text `json:"process"`
	RoastLevel      pgtype.Text `json:"roast_level"`
	TastingNotes    []string    `json:"tasting_notes"`
	PriceCents      pgtype.Int4 `json:"price_cents"`
	WeightGrams     pgtype.Int4 `json:"weight_grams"`
	InStock         bool        `json:"in_stock"`
	Variety         pgtype.Text `json:"variety"`
	Species         pgtype.Text `json:"species"`
	PricePer100gMin pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend         bool        `json:"is_blend"`
	IsDecaf         bool        `json:"is_decaf"`
	RoasterName     string      `json:"roaster_name"`
	RoasterSlug     string      `json:"roaster_slug"`
	RoasterLogoUrl  pgtype.Text `json:"roaster_logo_url"`
	CountryName     pgtype.Text `json:"country_name"`
	RegionName      pgtype.Text `json:"region_name"`
	CoffeeRegionID  pgtype.Int4 `json:"coffee_region_id"`
	ProducerName    pgtype.Text `json:"producer_name"`
	CoffeeProducerID pgtype.Int4 `json:"coffee_producer_id"`
}

func (q *Queries) ListCoffeesByRoasterWithAvailability(ctx context.Context, slug string) ([]ListCoffeesByRoasterWithAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listCoffeesByRoasterWithAvailability, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffeesByRoasterWithAvailabilityRow{}
	for rows.Next() {
		var i ListCoffeesByRoasterWithAvailabilityRow
		if err := rows.Scan(
			&i.ID, &i.RoasterID, &i.Name, &i.ProductUrl, &i.ImageUrl,
			&i.CountryCode, &i.OriginRaw, &i.RegionRaw, &i.Process, &i.RoastLevel,
			&i.TastingNotes, &i.PriceCents, &i.WeightGrams, &i.InStock,
			&i.Variety, &i.Species,
			&i.PricePer100gMin, &i.PricePer100gMax, &i.IsBlend, &i.IsDecaf,
			&i.RoasterName, &i.RoasterSlug, &i.RoasterLogoUrl,
			&i.CountryName,
			&i.RegionName, &i.CoffeeRegionID,
			&i.ProducerName, &i.CoffeeProducerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
