// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blend_components.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBlendComponents = `-- name: DeleteBlendComponents :exec
DELETE FROM blend_components WHERE coffee_id = $1
`

func (q *Queries) DeleteBlendComponents(ctx context.Context, coffeeID int32) error {
	_, err := q.db.Exec(ctx, deleteBlendComponents, coffeeID)
	return err
}

const insertBlendComponent = `-- name: InsertBlendComponent :exec
INSERT INTO blend_components (coffee_id, country_code, region_id, variety, percentage)
VALUES ($1, $2, $3, $4, $5)
`

type InsertBlendComponentParams struct {
	CoffeeID    int32       `json:"coffee_id"`
	CountryCode pgtype.Text `json:"country_code"`
	RegionID    pgtype.Int4 `json:"region_id"`
	Variety     pgtype.Text `json:"variety"`
	Percentage  pgtype.Int4 `json:"percentage"`
}

func (q *Queries) InsertBlendComponent(ctx context.Context, arg InsertBlendComponentParams) error {
	_, err := q.db.Exec(ctx, insertBlendComponent,
		arg.CoffeeID,
		arg.CountryCode,
		arg.RegionID,
		arg.Variety,
		arg.Percentage,
	)
	return err
}

const listBlendComponents = `-- name: ListBlendComponents :many
SELECT
    bc.id, bc.coffee_id, bc.country_code, bc.region_id,
    bc.variety, bc.percentage,
    co.name AS country_name,
    reg.name AS region_name
FROM blend_components bc
LEFT JOIN countries co ON co.code = bc.country_code
LEFT JOIN regions reg ON reg.id = bc.region_id
WHERE bc.coffee_id = $1
ORDER BY bc.id
`

type ListBlendComponentsRow struct {
	ID          int32       `json:"id"`
	CoffeeID    int32       `json:"coffee_id"`
	CountryCode pgtype.Text `json:"country_code"`
	RegionID    pgtype.Int4 `json:"region_id"`
	Variety     pgtype.Text `json:"variety"`
	Percentage  pgtype.Int4 `json:"percentage"`
	CountryName pgtype.Text `json:"country_name"`
	RegionName  pgtype.Text `json:"region_name"`
}

func (q *Queries) ListBlendComponents(ctx context.Context, coffeeID int32) ([]ListBlendComponentsRow, error) {
	rows, err := q.db.Query(ctx, listBlendComponents, coffeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlendComponentsRow{}
	for rows.Next() {
		var i ListBlendComponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CoffeeID,
			&i.CountryCode,
			&i.RegionID,
			&i.Variety,
			&i.Percentage,
			&i.CountryName,
			&i.RegionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
