// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brew_recipes.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrewRecipe = `-- name: CreateBrewRecipe :one
INSERT INTO brew_recipes (
    coffee_id, user_id, title, brew_method,
    dose_grams, water_ml, water_temp_c, grind_size,
    brew_time_seconds, notes, is_public
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, coffee_id, user_id, title, brew_method, dose_grams, water_ml, water_temp_c, grind_size, brew_time_seconds, notes, is_public, created_at, updated_at
`

type CreateBrewRecipeParams struct {
	CoffeeID        int64         `json:"coffee_id"`
	UserID          int32         `json:"user_id"`
	Title           string        `json:"title"`
	BrewMethod      string        `json:"brew_method"`
	DoseGrams       pgtype.Numeric `json:"dose_grams"`
	WaterMl         pgtype.Int4   `json:"water_ml"`
	WaterTempC      pgtype.Int4   `json:"water_temp_c"`
	GrindSize       pgtype.Text   `json:"grind_size"`
	BrewTimeSeconds pgtype.Int4   `json:"brew_time_seconds"`
	Notes           pgtype.Text   `json:"notes"`
	IsPublic        bool          `json:"is_public"`
}

func (q *Queries) CreateBrewRecipe(ctx context.Context, arg CreateBrewRecipeParams) (BrewRecipe, error) {
	row := q.db.QueryRow(ctx, createBrewRecipe,
		arg.CoffeeID,
		arg.UserID,
		arg.Title,
		arg.BrewMethod,
		arg.DoseGrams,
		arg.WaterMl,
		arg.WaterTempC,
		arg.GrindSize,
		arg.BrewTimeSeconds,
		arg.Notes,
		arg.IsPublic,
	)
	var i BrewRecipe
	err := row.Scan(
		&i.ID, &i.CoffeeID, &i.UserID, &i.Title, &i.BrewMethod,
		&i.DoseGrams, &i.WaterMl, &i.WaterTempC, &i.GrindSize,
		&i.BrewTimeSeconds, &i.Notes, &i.IsPublic, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const updateBrewRecipe = `-- name: UpdateBrewRecipe :one
UPDATE brew_recipes SET
    title = $3,
    brew_method = $4,
    dose_grams = $5,
    water_ml = $6,
    water_temp_c = $7,
    grind_size = $8,
    brew_time_seconds = $9,
    notes = $10,
    is_public = $11,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, coffee_id, user_id, title, brew_method, dose_grams, water_ml, water_temp_c, grind_size, brew_time_seconds, notes, is_public, created_at, updated_at
`

type UpdateBrewRecipeParams struct {
	ID              int32         `json:"id"`
	UserID          int32         `json:"user_id"`
	Title           string        `json:"title"`
	BrewMethod      string        `json:"brew_method"`
	DoseGrams       pgtype.Numeric `json:"dose_grams"`
	WaterMl         pgtype.Int4   `json:"water_ml"`
	WaterTempC      pgtype.Int4   `json:"water_temp_c"`
	GrindSize       pgtype.Text   `json:"grind_size"`
	BrewTimeSeconds pgtype.Int4   `json:"brew_time_seconds"`
	Notes           pgtype.Text   `json:"notes"`
	IsPublic        bool          `json:"is_public"`
}

func (q *Queries) UpdateBrewRecipe(ctx context.Context, arg UpdateBrewRecipeParams) (BrewRecipe, error) {
	row := q.db.QueryRow(ctx, updateBrewRecipe,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.BrewMethod,
		arg.DoseGrams,
		arg.WaterMl,
		arg.WaterTempC,
		arg.GrindSize,
		arg.BrewTimeSeconds,
		arg.Notes,
		arg.IsPublic,
	)
	var i BrewRecipe
	err := row.Scan(
		&i.ID, &i.CoffeeID, &i.UserID, &i.Title, &i.BrewMethod,
		&i.DoseGrams, &i.WaterMl, &i.WaterTempC, &i.GrindSize,
		&i.BrewTimeSeconds, &i.Notes, &i.IsPublic, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const deleteBrewRecipe = `-- name: DeleteBrewRecipe :exec
DELETE FROM brew_recipes
WHERE id = $1 AND user_id = $2
`

type DeleteBrewRecipeParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteBrewRecipe(ctx context.Context, arg DeleteBrewRecipeParams) error {
	_, err := q.db.Exec(ctx, deleteBrewRecipe, arg.ID, arg.UserID)
	return err
}

const getBrewRecipe = `-- name: GetBrewRecipe :one
SELECT br.id, br.coffee_id, br.user_id, br.title, br.brew_method, br.dose_grams, br.water_ml, br.water_temp_c, br.grind_size, br.brew_time_seconds, br.notes, br.is_public, br.created_at, br.updated_at,
       u.email AS user_email
FROM brew_recipes br
JOIN users u ON u.id = br.user_id
WHERE br.id = $1
`

type GetBrewRecipeRow struct {
	ID              int32         `json:"id"`
	CoffeeID        int64         `json:"coffee_id"`
	UserID          int32         `json:"user_id"`
	Title           string        `json:"title"`
	BrewMethod      string        `json:"brew_method"`
	DoseGrams       pgtype.Numeric `json:"dose_grams"`
	WaterMl         pgtype.Int4   `json:"water_ml"`
	WaterTempC      pgtype.Int4   `json:"water_temp_c"`
	GrindSize       pgtype.Text   `json:"grind_size"`
	BrewTimeSeconds pgtype.Int4   `json:"brew_time_seconds"`
	Notes           pgtype.Text   `json:"notes"`
	IsPublic        bool          `json:"is_public"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	UserEmail       string        `json:"user_email"`
}

func (q *Queries) GetBrewRecipe(ctx context.Context, id int32) (GetBrewRecipeRow, error) {
	row := q.db.QueryRow(ctx, getBrewRecipe, id)
	var i GetBrewRecipeRow
	err := row.Scan(
		&i.ID, &i.CoffeeID, &i.UserID, &i.Title, &i.BrewMethod,
		&i.DoseGrams, &i.WaterMl, &i.WaterTempC, &i.GrindSize,
		&i.BrewTimeSeconds, &i.Notes, &i.IsPublic, &i.CreatedAt, &i.UpdatedAt,
		&i.UserEmail,
	)
	return i, err
}

const listBrewRecipesByCoffee = `-- name: ListBrewRecipesByCoffee :many
SELECT br.id, br.coffee_id, br.user_id, br.title, br.brew_method, br.dose_grams, br.water_ml, br.water_temp_c, br.grind_size, br.brew_time_seconds, br.notes, br.is_public, br.created_at, br.updated_at,
       u.email AS user_email
FROM brew_recipes br
JOIN users u ON u.id = br.user_id
WHERE br.coffee_id = $1
    AND (br.is_public = true OR br.user_id = $2)
ORDER BY br.created_at DESC
`

type ListBrewRecipesByCoffeeParams struct {
	CoffeeID     int64       `json:"coffee_id"`
	ViewerUserID pgtype.Int4 `json:"viewer_user_id"`
}

type ListBrewRecipesByCoffeeRow struct {
	ID              int32         `json:"id"`
	CoffeeID        int64         `json:"coffee_id"`
	UserID          int32         `json:"user_id"`
	Title           string        `json:"title"`
	BrewMethod      string        `json:"brew_method"`
	DoseGrams       pgtype.Numeric `json:"dose_grams"`
	WaterMl         pgtype.Int4   `json:"water_ml"`
	WaterTempC      pgtype.Int4   `json:"water_temp_c"`
	GrindSize       pgtype.Text   `json:"grind_size"`
	BrewTimeSeconds pgtype.Int4   `json:"brew_time_seconds"`
	Notes           pgtype.Text   `json:"notes"`
	IsPublic        bool          `json:"is_public"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	UserEmail       string        `json:"user_email"`
}

func (q *Queries) ListBrewRecipesByCoffee(ctx context.Context, arg ListBrewRecipesByCoffeeParams) ([]ListBrewRecipesByCoffeeRow, error) {
	rows, err := q.db.Query(ctx, listBrewRecipesByCoffee, arg.CoffeeID, arg.ViewerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrewRecipesByCoffeeRow{}
	for rows.Next() {
		var i ListBrewRecipesByCoffeeRow
		if err := rows.Scan(
			&i.ID, &i.CoffeeID, &i.UserID, &i.Title, &i.BrewMethod,
			&i.DoseGrams, &i.WaterMl, &i.WaterTempC, &i.GrindSize,
			&i.BrewTimeSeconds, &i.Notes, &i.IsPublic, &i.CreatedAt, &i.UpdatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrewRecipesByUser = `-- name: ListBrewRecipesByUser :many
SELECT br.id, br.coffee_id, br.user_id, br.title, br.brew_method, br.dose_grams, br.water_ml, br.water_temp_c, br.grind_size, br.brew_time_seconds, br.notes, br.is_public, br.created_at, br.updated_at,
       c.name AS coffee_name,
       r.name AS roaster_name, r.slug AS roaster_slug
FROM brew_recipes br
JOIN coffees c ON c.id = br.coffee_id
JOIN roasters r ON r.id = c.roaster_id
WHERE br.user_id = $1
ORDER BY br.updated_at DESC
`

type ListBrewRecipesByUserRow struct {
	ID              int32         `json:"id"`
	CoffeeID        int64         `json:"coffee_id"`
	UserID          int32         `json:"user_id"`
	Title           string        `json:"title"`
	BrewMethod      string        `json:"brew_method"`
	DoseGrams       pgtype.Numeric `json:"dose_grams"`
	WaterMl         pgtype.Int4   `json:"water_ml"`
	WaterTempC      pgtype.Int4   `json:"water_temp_c"`
	GrindSize       pgtype.Text   `json:"grind_size"`
	BrewTimeSeconds pgtype.Int4   `json:"brew_time_seconds"`
	Notes           pgtype.Text   `json:"notes"`
	IsPublic        bool          `json:"is_public"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	CoffeeName      string        `json:"coffee_name"`
	RoasterName     string        `json:"roaster_name"`
	RoasterSlug     string        `json:"roaster_slug"`
}

func (q *Queries) ListBrewRecipesByUser(ctx context.Context, userID int32) ([]ListBrewRecipesByUserRow, error) {
	rows, err := q.db.Query(ctx, listBrewRecipesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrewRecipesByUserRow{}
	for rows.Next() {
		var i ListBrewRecipesByUserRow
		if err := rows.Scan(
			&i.ID, &i.CoffeeID, &i.UserID, &i.Title, &i.BrewMethod,
			&i.DoseGrams, &i.WaterMl, &i.WaterTempC, &i.GrindSize,
			&i.BrewTimeSeconds, &i.Notes, &i.IsPublic, &i.CreatedAt, &i.UpdatedAt,
			&i.CoffeeName, &i.RoasterName, &i.RoasterSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
