// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cafes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCafes = `-- name: CountCafes :one
SELECT count(*) FROM cafes WHERE active = true
`

func (q *Queries) CountCafes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCafes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCafeBySlug = `-- name: GetCafeBySlug :one
SELECT c.id, c.roaster_id, c.slug, c.name, c.type, c.address, c.suburb, c.state, c.postcode,
       c.latitude, c.longitude, c.phone, c.instagram, c.website_url, c.image_url,
       r.name AS roaster_name, r.slug AS roaster_slug
FROM cafes c
JOIN roasters r ON r.id = c.roaster_id
WHERE c.slug = $1 AND c.active = true
`

type GetCafeBySlugRow struct {
	ID          int32         `json:"id"`
	RoasterID   int32         `json:"roaster_id"`
	Slug        string        `json:"slug"`
	Name        string        `json:"name"`
	Type        string        `json:"type"`
	Address     pgtype.Text   `json:"address"`
	Suburb      pgtype.Text   `json:"suburb"`
	State       pgtype.Text   `json:"state"`
	Postcode    pgtype.Text   `json:"postcode"`
	Latitude    pgtype.Float8 `json:"latitude"`
	Longitude   pgtype.Float8 `json:"longitude"`
	Phone       pgtype.Text   `json:"phone"`
	Instagram   pgtype.Text   `json:"instagram"`
	WebsiteUrl  pgtype.Text   `json:"website_url"`
	ImageUrl    pgtype.Text   `json:"image_url"`
	RoasterName string        `json:"roaster_name"`
	RoasterSlug string        `json:"roaster_slug"`
}

func (q *Queries) GetCafeBySlug(ctx context.Context, slug string) (GetCafeBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCafeBySlug, slug)
	var i GetCafeBySlugRow
	err := row.Scan(
		&i.ID,
		&i.RoasterID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.Address,
		&i.Suburb,
		&i.State,
		&i.Postcode,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Instagram,
		&i.WebsiteUrl,
		&i.ImageUrl,
		&i.RoasterName,
		&i.RoasterSlug,
	)
	return i, err
}

const listCafes = `-- name: ListCafes :many
SELECT c.id, c.slug, c.name, c.type, c.address, c.suburb, c.state, c.postcode,
       c.latitude, c.longitude, c.phone, c.instagram, c.website_url, c.image_url,
       r.id AS roaster_id, r.name AS roaster_name, r.slug AS roaster_slug
FROM cafes c
JOIN roasters r ON r.id = c.roaster_id
WHERE c.active = true AND r.active = true AND r.opted_out = false
ORDER BY c.type, c.state, c.name
`

type ListCafesRow struct {
	ID          int32         `json:"id"`
	Slug        string        `json:"slug"`
	Name        string        `json:"name"`
	Type        string        `json:"type"`
	Address     pgtype.Text   `json:"address"`
	Suburb      pgtype.Text   `json:"suburb"`
	State       pgtype.Text   `json:"state"`
	Postcode    pgtype.Text   `json:"postcode"`
	Latitude    pgtype.Float8 `json:"latitude"`
	Longitude   pgtype.Float8 `json:"longitude"`
	Phone       pgtype.Text   `json:"phone"`
	Instagram   pgtype.Text   `json:"instagram"`
	WebsiteUrl  pgtype.Text   `json:"website_url"`
	ImageUrl    pgtype.Text   `json:"image_url"`
	RoasterID   int32         `json:"roaster_id"`
	RoasterName string        `json:"roaster_name"`
	RoasterSlug string        `json:"roaster_slug"`
}

func (q *Queries) ListCafes(ctx context.Context) ([]ListCafesRow, error) {
	rows, err := q.db.Query(ctx, listCafes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCafesRow{}
	for rows.Next() {
		var i ListCafesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Address,
			&i.Suburb,
			&i.State,
			&i.Postcode,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Instagram,
			&i.WebsiteUrl,
			&i.ImageUrl,
			&i.RoasterID,
			&i.RoasterName,
			&i.RoasterSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCafesByState = `-- name: ListCafesByState :many
SELECT c.id, c.slug, c.name, c.type, c.address, c.suburb, c.state, c.postcode,
       c.latitude, c.longitude, c.phone, c.instagram, c.website_url, c.image_url,
       r.id AS roaster_id, r.name AS roaster_name, r.slug AS roaster_slug
FROM cafes c
JOIN roasters r ON r.id = c.roaster_id
WHERE c.state = $1 AND c.active = true AND r.active = true AND r.opted_out = false
ORDER BY c.type, c.name
`

type ListCafesByStateRow struct {
	ID          int32         `json:"id"`
	Slug        string        `json:"slug"`
	Name        string        `json:"name"`
	Type        string        `json:"type"`
	Address     pgtype.Text   `json:"address"`
	Suburb      pgtype.Text   `json:"suburb"`
	State       pgtype.Text   `json:"state"`
	Postcode    pgtype.Text   `json:"postcode"`
	Latitude    pgtype.Float8 `json:"latitude"`
	Longitude   pgtype.Float8 `json:"longitude"`
	Phone       pgtype.Text   `json:"phone"`
	Instagram   pgtype.Text   `json:"instagram"`
	WebsiteUrl  pgtype.Text   `json:"website_url"`
	ImageUrl    pgtype.Text   `json:"image_url"`
	RoasterID   int32         `json:"roaster_id"`
	RoasterName string        `json:"roaster_name"`
	RoasterSlug string        `json:"roaster_slug"`
}

func (q *Queries) ListCafesByState(ctx context.Context, state pgtype.Text) ([]ListCafesByStateRow, error) {
	rows, err := q.db.Query(ctx, listCafesByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCafesByStateRow{}
	for rows.Next() {
		var i ListCafesByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Address,
			&i.Suburb,
			&i.State,
			&i.Postcode,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Instagram,
			&i.WebsiteUrl,
			&i.ImageUrl,
			&i.RoasterID,
			&i.RoasterName,
			&i.RoasterSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCafesByRoaster = `-- name: ListCafesByRoaster :many
SELECT c.id, c.slug, c.name, c.type, c.address, c.suburb, c.state, c.postcode,
       c.latitude, c.longitude, c.phone, c.instagram, c.website_url, c.image_url
FROM cafes c
WHERE c.roaster_id = $1 AND c.active = true
ORDER BY c.type, c.name
`

type ListCafesByRoasterRow struct {
	ID         int32         `json:"id"`
	Slug       string        `json:"slug"`
	Name       string        `json:"name"`
	Type       string        `json:"type"`
	Address    pgtype.Text   `json:"address"`
	Suburb     pgtype.Text   `json:"suburb"`
	State      pgtype.Text   `json:"state"`
	Postcode   pgtype.Text   `json:"postcode"`
	Latitude   pgtype.Float8 `json:"latitude"`
	Longitude  pgtype.Float8 `json:"longitude"`
	Phone      pgtype.Text   `json:"phone"`
	Instagram  pgtype.Text   `json:"instagram"`
	WebsiteUrl pgtype.Text   `json:"website_url"`
	ImageUrl   pgtype.Text   `json:"image_url"`
}

func (q *Queries) ListCafesByRoaster(ctx context.Context, roasterID int32) ([]ListCafesByRoasterRow, error) {
	rows, err := q.db.Query(ctx, listCafesByRoaster, roasterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCafesByRoasterRow{}
	for rows.Next() {
		var i ListCafesByRoasterRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Address,
			&i.Suburb,
			&i.State,
			&i.Postcode,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Instagram,
			&i.WebsiteUrl,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCafe = `-- name: UpsertCafe :one
INSERT INTO cafes (roaster_id, slug, name, type, address, suburb, state, postcode, latitude, longitude, phone, instagram, website_url, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (roaster_id, slug) DO UPDATE SET
    name = EXCLUDED.name,
    type = EXCLUDED.type,
    address = EXCLUDED.address,
    suburb = EXCLUDED.suburb,
    state = EXCLUDED.state,
    postcode = EXCLUDED.postcode,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    phone = EXCLUDED.phone,
    instagram = EXCLUDED.instagram,
    website_url = EXCLUDED.website_url,
    image_url = EXCLUDED.image_url,
    updated_at = now()
RETURNING id
`

type UpsertCafeParams struct {
	RoasterID  int32         `json:"roaster_id"`
	Slug       string        `json:"slug"`
	Name       string        `json:"name"`
	Type       string        `json:"type"`
	Address    pgtype.Text   `json:"address"`
	Suburb     pgtype.Text   `json:"suburb"`
	State      pgtype.Text   `json:"state"`
	Postcode   pgtype.Text   `json:"postcode"`
	Latitude   pgtype.Float8 `json:"latitude"`
	Longitude  pgtype.Float8 `json:"longitude"`
	Phone      pgtype.Text   `json:"phone"`
	Instagram  pgtype.Text   `json:"instagram"`
	WebsiteUrl pgtype.Text   `json:"website_url"`
	ImageUrl   pgtype.Text   `json:"image_url"`
}

func (q *Queries) UpsertCafe(ctx context.Context, arg UpsertCafeParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertCafe,
		arg.RoasterID,
		arg.Slug,
		arg.Name,
		arg.Type,
		arg.Address,
		arg.Suburb,
		arg.State,
		arg.Postcode,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Instagram,
		arg.WebsiteUrl,
		arg.ImageUrl,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
