// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coffees.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCoffees = `-- name: CountCoffees :one
SELECT count(*)
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
WHERE r.opted_out = false
    AND c.in_stock = true
`

func (q *Queries) CountCoffees(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCoffees)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filterCoffees = `-- name: FilterCoffees :many
SELECT
    c.id, c.roaster_id, c.name, c.product_url, c.image_url,
    c.country_code, c.origin_raw, c.region_raw, c.process, c.roast_level,
    c.tasting_notes, c.price_cents, c.weight_grams, c.in_stock,
    c.variety, c.species,
    c.price_per_100g_min, c.price_per_100g_max, c.is_blend,
    r.name AS roaster_name, r.slug AS roaster_slug,
    co.name AS country_name,
    reg.name AS region_name, reg.id AS coffee_region_id,
    p.name AS producer_name, p.id AS coffee_producer_id
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN countries co ON co.code = c.country_code
LEFT JOIN regions reg ON reg.id = c.region_id
LEFT JOIN producers p ON p.id = c.producer_id
WHERE r.opted_out = false
    AND ($1::text IS NULL OR c.country_code = $1
        OR (c.is_blend AND EXISTS (
            SELECT 1 FROM blend_components bc
            WHERE bc.coffee_id = c.id AND bc.country_code = $1)))
    AND ($2::text IS NULL OR c.process = $2)
    AND ($3::text IS NULL OR c.roast_level = $3)
    AND ($4::boolean IS NULL OR c.in_stock = $4)
    AND ($5::text IS NULL OR c.variety = $5)
ORDER BY c.name
LIMIT $6 OFFSET $7
`

type FilterCoffeesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 bool   `json:"column_4"`
	Column5 string `json:"column_5"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type FilterCoffeesRow struct {
	ID               int64       `json:"id"`
	RoasterID        int32       `json:"roaster_id"`
	Name             string      `json:"name"`
	ProductUrl       pgtype.Text `json:"product_url"`
	ImageUrl         pgtype.Text `json:"image_url"`
	CountryCode      pgtype.Text `json:"country_code"`
	OriginRaw        pgtype.Text `json:"origin_raw"`
	RegionRaw        pgtype.Text `json:"region_raw"`
	Process          pgtype.Text `json:"process"`
	RoastLevel       pgtype.Text `json:"roast_level"`
	TastingNotes     []string    `json:"tasting_notes"`
	PriceCents       pgtype.Int4 `json:"price_cents"`
	WeightGrams      pgtype.Int4 `json:"weight_grams"`
	InStock          bool        `json:"in_stock"`
	Variety          pgtype.Text `json:"variety"`
	Species          pgtype.Text `json:"species"`
	PricePer100gMin  pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax  pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend          bool        `json:"is_blend"`
	RoasterName      string      `json:"roaster_name"`
	RoasterSlug      string      `json:"roaster_slug"`
	CountryName      pgtype.Text `json:"country_name"`
	RegionName       pgtype.Text `json:"region_name"`
	CoffeeRegionID   pgtype.Int4 `json:"coffee_region_id"`
	ProducerName     pgtype.Text `json:"producer_name"`
	CoffeeProducerID pgtype.Int4 `json:"coffee_producer_id"`
}

func (q *Queries) FilterCoffees(ctx context.Context, arg FilterCoffeesParams) ([]FilterCoffeesRow, error) {
	rows, err := q.db.Query(ctx, filterCoffees,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterCoffeesRow{}
	for rows.Next() {
		var i FilterCoffeesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoasterID,
			&i.Name,
			&i.ProductUrl,
			&i.ImageUrl,
			&i.CountryCode,
			&i.OriginRaw,
			&i.RegionRaw,
			&i.Process,
			&i.RoastLevel,
			&i.TastingNotes,
			&i.PriceCents,
			&i.WeightGrams,
			&i.InStock,
			&i.Variety,
			&i.Species,
			&i.PricePer100gMin,
			&i.PricePer100gMax,
			&i.IsBlend,
			&i.RoasterName,
			&i.RoasterSlug,
			&i.CountryName,
			&i.RegionName,
			&i.CoffeeRegionID,
			&i.ProducerName,
			&i.CoffeeProducerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoffeeByID = `-- name: GetCoffeeByID :one
SELECT
    c.id, c.roaster_id, c.name, c.product_url, c.image_url,
    c.origin_raw, c.region_raw, c.variety_raw, c.process_raw, c.roast_raw,
    c.tasting_notes_raw, c.country_code, c.process, c.roast_level,
    c.tasting_notes, c.price_cents, c.weight_grams, c.in_stock,
    c.producer_raw, c.region_id, c.producer_id,
    c.variety, c.species,
    c.price_per_100g_min, c.price_per_100g_max, c.is_blend,
    c.first_seen_at, c.last_seen_at,
    r.name AS roaster_name, r.slug AS roaster_slug,
    co.name AS country_name,
    reg.name AS region_name,
    p.name AS producer_name
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN countries co ON co.code = c.country_code
LEFT JOIN regions reg ON reg.id = c.region_id
LEFT JOIN producers p ON p.id = c.producer_id
WHERE c.id = $1
`

type GetCoffeeByIDRow struct {
	ID              int64       `json:"id"`
	RoasterID       int32       `json:"roaster_id"`
	Name            string      `json:"name"`
	ProductUrl      pgtype.Text `json:"product_url"`
	ImageUrl        pgtype.Text `json:"image_url"`
	OriginRaw       pgtype.Text `json:"origin_raw"`
	RegionRaw       pgtype.Text `json:"region_raw"`
	VarietyRaw      pgtype.Text `json:"variety_raw"`
	ProcessRaw      pgtype.Text `json:"process_raw"`
	RoastRaw        pgtype.Text `json:"roast_raw"`
	TastingNotesRaw pgtype.Text `json:"tasting_notes_raw"`
	CountryCode     pgtype.Text `json:"country_code"`
	Process         pgtype.Text `json:"process"`
	RoastLevel      pgtype.Text `json:"roast_level"`
	TastingNotes    []string    `json:"tasting_notes"`
	PriceCents      pgtype.Int4 `json:"price_cents"`
	WeightGrams     pgtype.Int4 `json:"weight_grams"`
	InStock         bool        `json:"in_stock"`
	ProducerRaw     pgtype.Text `json:"producer_raw"`
	RegionID        pgtype.Int4 `json:"region_id"`
	ProducerID      pgtype.Int4 `json:"producer_id"`
	Variety         pgtype.Text `json:"variety"`
	Species         pgtype.Text `json:"species"`
	PricePer100gMin pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend         bool        `json:"is_blend"`
	FirstSeenAt     time.Time   `json:"first_seen_at"`
	LastSeenAt      time.Time   `json:"last_seen_at"`
	RoasterName     string      `json:"roaster_name"`
	RoasterSlug     string      `json:"roaster_slug"`
	CountryName     pgtype.Text `json:"country_name"`
	RegionName      pgtype.Text `json:"region_name"`
	ProducerName    pgtype.Text `json:"producer_name"`
}

func (q *Queries) GetCoffeeByID(ctx context.Context, id int64) (GetCoffeeByIDRow, error) {
	row := q.db.QueryRow(ctx, getCoffeeByID, id)
	var i GetCoffeeByIDRow
	err := row.Scan(
		&i.ID,
		&i.RoasterID,
		&i.Name,
		&i.ProductUrl,
		&i.ImageUrl,
		&i.OriginRaw,
		&i.RegionRaw,
		&i.VarietyRaw,
		&i.ProcessRaw,
		&i.RoastRaw,
		&i.TastingNotesRaw,
		&i.CountryCode,
		&i.Process,
		&i.RoastLevel,
		&i.TastingNotes,
		&i.PriceCents,
		&i.WeightGrams,
		&i.InStock,
		&i.ProducerRaw,
		&i.RegionID,
		&i.ProducerID,
		&i.Variety,
		&i.Species,
		&i.PricePer100gMin,
		&i.PricePer100gMax,
		&i.IsBlend,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.RoasterName,
		&i.RoasterSlug,
		&i.CountryName,
		&i.RegionName,
		&i.ProducerName,
	)
	return i, err
}

const listCoffees = `-- name: ListCoffees :many
SELECT
    c.id, c.roaster_id, c.name, c.product_url, c.image_url,
    c.country_code, c.origin_raw, c.region_raw, c.process, c.roast_level,
    c.tasting_notes, c.price_cents, c.weight_grams, c.in_stock,
    c.variety, c.species,
    c.price_per_100g_min, c.price_per_100g_max, c.is_blend,
    r.name AS roaster_name, r.slug AS roaster_slug,
    co.name AS country_name,
    reg.name AS region_name, reg.id AS coffee_region_id,
    p.name AS producer_name, p.id AS coffee_producer_id
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN countries co ON co.code = c.country_code
LEFT JOIN regions reg ON reg.id = c.region_id
LEFT JOIN producers p ON p.id = c.producer_id
WHERE r.opted_out = false
    AND c.in_stock = true
ORDER BY c.name
LIMIT $1 OFFSET $2
`

type ListCoffeesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCoffeesRow struct {
	ID               int64       `json:"id"`
	RoasterID        int32       `json:"roaster_id"`
	Name             string      `json:"name"`
	ProductUrl       pgtype.Text `json:"product_url"`
	ImageUrl         pgtype.Text `json:"image_url"`
	CountryCode      pgtype.Text `json:"country_code"`
	OriginRaw        pgtype.Text `json:"origin_raw"`
	RegionRaw        pgtype.Text `json:"region_raw"`
	Process          pgtype.Text `json:"process"`
	RoastLevel       pgtype.Text `json:"roast_level"`
	TastingNotes     []string    `json:"tasting_notes"`
	PriceCents       pgtype.Int4 `json:"price_cents"`
	WeightGrams      pgtype.Int4 `json:"weight_grams"`
	InStock          bool        `json:"in_stock"`
	Variety          pgtype.Text `json:"variety"`
	Species          pgtype.Text `json:"species"`
	PricePer100gMin  pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax  pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend          bool        `json:"is_blend"`
	RoasterName      string      `json:"roaster_name"`
	RoasterSlug      string      `json:"roaster_slug"`
	CountryName      pgtype.Text `json:"country_name"`
	RegionName       pgtype.Text `json:"region_name"`
	CoffeeRegionID   pgtype.Int4 `json:"coffee_region_id"`
	ProducerName     pgtype.Text `json:"producer_name"`
	CoffeeProducerID pgtype.Int4 `json:"coffee_producer_id"`
}

func (q *Queries) ListCoffees(ctx context.Context, arg ListCoffeesParams) ([]ListCoffeesRow, error) {
	rows, err := q.db.Query(ctx, listCoffees, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffeesRow{}
	for rows.Next() {
		var i ListCoffeesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoasterID,
			&i.Name,
			&i.ProductUrl,
			&i.ImageUrl,
			&i.CountryCode,
			&i.OriginRaw,
			&i.RegionRaw,
			&i.Process,
			&i.RoastLevel,
			&i.TastingNotes,
			&i.PriceCents,
			&i.WeightGrams,
			&i.InStock,
			&i.Variety,
			&i.Species,
			&i.PricePer100gMin,
			&i.PricePer100gMax,
			&i.IsBlend,
			&i.RoasterName,
			&i.RoasterSlug,
			&i.CountryName,
			&i.RegionName,
			&i.CoffeeRegionID,
			&i.ProducerName,
			&i.CoffeeProducerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoffeesByCountry = `-- name: ListCoffeesByCountry :many
SELECT
    c.id, c.roaster_id, c.name, c.product_url, c.image_url,
    c.country_code, c.process, c.roast_level,
    c.tasting_notes, c.price_cents, c.weight_grams, c.in_stock,
    c.variety, c.species,
    c.price_per_100g_min, c.price_per_100g_max, c.is_blend,
    r.name AS roaster_name, r.slug AS roaster_slug,
    co.name AS country_name,
    reg.name AS region_name, reg.id AS coffee_region_id,
    p.name AS producer_name, p.id AS coffee_producer_id
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN countries co ON co.code = c.country_code
LEFT JOIN regions reg ON reg.id = c.region_id
LEFT JOIN producers p ON p.id = c.producer_id
WHERE r.opted_out = false
    AND (c.country_code = $1
        OR (c.is_blend AND EXISTS (
            SELECT 1 FROM blend_components bc
            WHERE bc.coffee_id = c.id AND bc.country_code = $1)))
ORDER BY c.name
`

type ListCoffeesByCountryRow struct {
	ID               int64       `json:"id"`
	RoasterID        int32       `json:"roaster_id"`
	Name             string      `json:"name"`
	ProductUrl       pgtype.Text `json:"product_url"`
	ImageUrl         pgtype.Text `json:"image_url"`
	CountryCode      pgtype.Text `json:"country_code"`
	Process          pgtype.Text `json:"process"`
	RoastLevel       pgtype.Text `json:"roast_level"`
	TastingNotes     []string    `json:"tasting_notes"`
	PriceCents       pgtype.Int4 `json:"price_cents"`
	WeightGrams      pgtype.Int4 `json:"weight_grams"`
	InStock          bool        `json:"in_stock"`
	Variety          pgtype.Text `json:"variety"`
	Species          pgtype.Text `json:"species"`
	PricePer100gMin  pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax  pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend          bool        `json:"is_blend"`
	RoasterName      string      `json:"roaster_name"`
	RoasterSlug      string      `json:"roaster_slug"`
	CountryName      pgtype.Text `json:"country_name"`
	RegionName       pgtype.Text `json:"region_name"`
	CoffeeRegionID   pgtype.Int4 `json:"coffee_region_id"`
	ProducerName     pgtype.Text `json:"producer_name"`
	CoffeeProducerID pgtype.Int4 `json:"coffee_producer_id"`
}

func (q *Queries) ListCoffeesByCountry(ctx context.Context, countryCode pgtype.Text) ([]ListCoffeesByCountryRow, error) {
	rows, err := q.db.Query(ctx, listCoffeesByCountry, countryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffeesByCountryRow{}
	for rows.Next() {
		var i ListCoffeesByCountryRow
		if err := rows.Scan(
			&i.ID,
			&i.RoasterID,
			&i.Name,
			&i.ProductUrl,
			&i.ImageUrl,
			&i.CountryCode,
			&i.Process,
			&i.RoastLevel,
			&i.TastingNotes,
			&i.PriceCents,
			&i.WeightGrams,
			&i.InStock,
			&i.Variety,
			&i.Species,
			&i.PricePer100gMin,
			&i.PricePer100gMax,
			&i.IsBlend,
			&i.RoasterName,
			&i.RoasterSlug,
			&i.CountryName,
			&i.RegionName,
			&i.CoffeeRegionID,
			&i.ProducerName,
			&i.CoffeeProducerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoffeesByProducer = `-- name: ListCoffeesByProducer :many
SELECT
    c.id, c.roaster_id, c.name, c.product_url, c.image_url,
    c.country_code, c.process, c.roast_level,
    c.tasting_notes, c.price_cents, c.weight_grams, c.in_stock,
    c.variety, c.species,
    c.price_per_100g_min, c.price_per_100g_max, c.is_blend,
    r.name AS roaster_name, r.slug AS roaster_slug,
    co.name AS country_name,
    reg.name AS region_name, reg.id AS coffee_region_id,
    p.name AS producer_name, p.id AS coffee_producer_id
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN countries co ON co.code = c.country_code
LEFT JOIN regions reg ON reg.id = c.region_id
LEFT JOIN producers p ON p.id = c.producer_id
WHERE c.producer_id = $1 AND r.opted_out = false
ORDER BY c.name
`

type ListCoffeesByProducerRow struct {
	ID               int64       `json:"id"`
	RoasterID        int32       `json:"roaster_id"`
	Name             string      `json:"name"`
	ProductUrl       pgtype.Text `json:"product_url"`
	ImageUrl         pgtype.Text `json:"image_url"`
	CountryCode      pgtype.Text `json:"country_code"`
	Process          pgtype.Text `json:"process"`
	RoastLevel       pgtype.Text `json:"roast_level"`
	TastingNotes     []string    `json:"tasting_notes"`
	PriceCents       pgtype.Int4 `json:"price_cents"`
	WeightGrams      pgtype.Int4 `json:"weight_grams"`
	InStock          bool        `json:"in_stock"`
	Variety          pgtype.Text `json:"variety"`
	Species          pgtype.Text `json:"species"`
	PricePer100gMin  pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax  pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend          bool        `json:"is_blend"`
	RoasterName      string      `json:"roaster_name"`
	RoasterSlug      string      `json:"roaster_slug"`
	CountryName      pgtype.Text `json:"country_name"`
	RegionName       pgtype.Text `json:"region_name"`
	CoffeeRegionID   pgtype.Int4 `json:"coffee_region_id"`
	ProducerName     pgtype.Text `json:"producer_name"`
	CoffeeProducerID pgtype.Int4 `json:"coffee_producer_id"`
}

func (q *Queries) ListCoffeesByProducer(ctx context.Context, producerID pgtype.Int4) ([]ListCoffeesByProducerRow, error) {
	rows, err := q.db.Query(ctx, listCoffeesByProducer, producerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffeesByProducerRow{}
	for rows.Next() {
		var i ListCoffeesByProducerRow
		if err := rows.Scan(
			&i.ID,
			&i.RoasterID,
			&i.Name,
			&i.ProductUrl,
			&i.ImageUrl,
			&i.CountryCode,
			&i.Process,
			&i.RoastLevel,
			&i.TastingNotes,
			&i.PriceCents,
			&i.WeightGrams,
			&i.InStock,
			&i.Variety,
			&i.Species,
			&i.PricePer100gMin,
			&i.PricePer100gMax,
			&i.IsBlend,
			&i.RoasterName,
			&i.RoasterSlug,
			&i.CountryName,
			&i.RegionName,
			&i.CoffeeRegionID,
			&i.ProducerName,
			&i.CoffeeProducerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoffeesByRegion = `-- name: ListCoffeesByRegion :many
SELECT
    c.id, c.roaster_id, c.name, c.product_url, c.image_url,
    c.country_code, c.process, c.roast_level,
    c.tasting_notes, c.price_cents, c.weight_grams, c.in_stock,
    c.variety, c.species,
    c.price_per_100g_min, c.price_per_100g_max, c.is_blend,
    r.name AS roaster_name, r.slug AS roaster_slug,
    co.name AS country_name,
    reg.name AS region_name, reg.id AS coffee_region_id,
    p.name AS producer_name, p.id AS coffee_producer_id
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN countries co ON co.code = c.country_code
LEFT JOIN regions reg ON reg.id = c.region_id
LEFT JOIN producers p ON p.id = c.producer_id
WHERE c.region_id = $1 AND r.opted_out = false
ORDER BY c.name
`

type ListCoffeesByRegionRow struct {
	ID               int64       `json:"id"`
	RoasterID        int32       `json:"roaster_id"`
	Name             string      `json:"name"`
	ProductUrl       pgtype.Text `json:"product_url"`
	ImageUrl         pgtype.Text `json:"image_url"`
	CountryCode      pgtype.Text `json:"country_code"`
	Process          pgtype.Text `json:"process"`
	RoastLevel       pgtype.Text `json:"roast_level"`
	TastingNotes     []string    `json:"tasting_notes"`
	PriceCents       pgtype.Int4 `json:"price_cents"`
	WeightGrams      pgtype.Int4 `json:"weight_grams"`
	InStock          bool        `json:"in_stock"`
	Variety          pgtype.Text `json:"variety"`
	Species          pgtype.Text `json:"species"`
	PricePer100gMin  pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax  pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend          bool        `json:"is_blend"`
	RoasterName      string      `json:"roaster_name"`
	RoasterSlug      string      `json:"roaster_slug"`
	CountryName      pgtype.Text `json:"country_name"`
	RegionName       pgtype.Text `json:"region_name"`
	CoffeeRegionID   pgtype.Int4 `json:"coffee_region_id"`
	ProducerName     pgtype.Text `json:"producer_name"`
	CoffeeProducerID pgtype.Int4 `json:"coffee_producer_id"`
}

func (q *Queries) ListCoffeesByRegion(ctx context.Context, regionID pgtype.Int4) ([]ListCoffeesByRegionRow, error) {
	rows, err := q.db.Query(ctx, listCoffeesByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffeesByRegionRow{}
	for rows.Next() {
		var i ListCoffeesByRegionRow
		if err := rows.Scan(
			&i.ID,
			&i.RoasterID,
			&i.Name,
			&i.ProductUrl,
			&i.ImageUrl,
			&i.CountryCode,
			&i.Process,
			&i.RoastLevel,
			&i.TastingNotes,
			&i.PriceCents,
			&i.WeightGrams,
			&i.InStock,
			&i.Variety,
			&i.Species,
			&i.PricePer100gMin,
			&i.PricePer100gMax,
			&i.IsBlend,
			&i.RoasterName,
			&i.RoasterSlug,
			&i.CountryName,
			&i.RegionName,
			&i.CoffeeRegionID,
			&i.ProducerName,
			&i.CoffeeProducerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoffeesByRoaster = `-- name: ListCoffeesByRoaster :many
SELECT
    c.id, c.roaster_id, c.name, c.product_url, c.image_url,
    c.country_code, c.origin_raw, c.region_raw, c.process, c.roast_level,
    c.tasting_notes, c.price_cents, c.weight_grams, c.in_stock,
    c.variety, c.species,
    c.price_per_100g_min, c.price_per_100g_max, c.is_blend,
    r.name AS roaster_name, r.slug AS roaster_slug,
    co.name AS country_name,
    reg.name AS region_name, reg.id AS coffee_region_id,
    p.name AS producer_name, p.id AS coffee_producer_id
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN countries co ON co.code = c.country_code
LEFT JOIN regions reg ON reg.id = c.region_id
LEFT JOIN producers p ON p.id = c.producer_id
WHERE r.slug = $1 AND r.opted_out = false
ORDER BY c.name
`

type ListCoffeesByRoasterRow struct {
	ID               int64       `json:"id"`
	RoasterID        int32       `json:"roaster_id"`
	Name             string      `json:"name"`
	ProductUrl       pgtype.Text `json:"product_url"`
	ImageUrl         pgtype.Text `json:"image_url"`
	CountryCode      pgtype.Text `json:"country_code"`
	OriginRaw        pgtype.Text `json:"origin_raw"`
	RegionRaw        pgtype.Text `json:"region_raw"`
	Process          pgtype.Text `json:"process"`
	RoastLevel       pgtype.Text `json:"roast_level"`
	TastingNotes     []string    `json:"tasting_notes"`
	PriceCents       pgtype.Int4 `json:"price_cents"`
	WeightGrams      pgtype.Int4 `json:"weight_grams"`
	InStock          bool        `json:"in_stock"`
	Variety          pgtype.Text `json:"variety"`
	Species          pgtype.Text `json:"species"`
	PricePer100gMin  pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax  pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend          bool        `json:"is_blend"`
	RoasterName      string      `json:"roaster_name"`
	RoasterSlug      string      `json:"roaster_slug"`
	CountryName      pgtype.Text `json:"country_name"`
	RegionName       pgtype.Text `json:"region_name"`
	CoffeeRegionID   pgtype.Int4 `json:"coffee_region_id"`
	ProducerName     pgtype.Text `json:"producer_name"`
	CoffeeProducerID pgtype.Int4 `json:"coffee_producer_id"`
}

func (q *Queries) ListCoffeesByRoaster(ctx context.Context, slug string) ([]ListCoffeesByRoasterRow, error) {
	rows, err := q.db.Query(ctx, listCoffeesByRoaster, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffeesByRoasterRow{}
	for rows.Next() {
		var i ListCoffeesByRoasterRow
		if err := rows.Scan(
			&i.ID,
			&i.RoasterID,
			&i.Name,
			&i.ProductUrl,
			&i.ImageUrl,
			&i.CountryCode,
			&i.OriginRaw,
			&i.RegionRaw,
			&i.Process,
			&i.RoastLevel,
			&i.TastingNotes,
			&i.PriceCents,
			&i.WeightGrams,
			&i.InStock,
			&i.Variety,
			&i.Species,
			&i.PricePer100gMin,
			&i.PricePer100gMax,
			&i.IsBlend,
			&i.RoasterName,
			&i.RoasterSlug,
			&i.CountryName,
			&i.RegionName,
			&i.CoffeeRegionID,
			&i.ProducerName,
			&i.CoffeeProducerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoffeesForSimilarity = `-- name: ListCoffeesForSimilarity :many
SELECT
    c.id, c.tasting_notes, c.process, c.roast_level, c.variety,
    c.region_id, reg.latitude, reg.longitude
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN regions reg ON reg.id = c.region_id
WHERE c.in_stock = true AND r.opted_out = false
`

type ListCoffeesForSimilarityRow struct {
	ID           int64         `json:"id"`
	TastingNotes []string      `json:"tasting_notes"`
	Process      pgtype.Text   `json:"process"`
	RoastLevel   pgtype.Text   `json:"roast_level"`
	Variety      pgtype.Text   `json:"variety"`
	RegionID     pgtype.Int4   `json:"region_id"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
}

func (q *Queries) ListCoffeesForSimilarity(ctx context.Context) ([]ListCoffeesForSimilarityRow, error) {
	rows, err := q.db.Query(ctx, listCoffeesForSimilarity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffeesForSimilarityRow{}
	for rows.Next() {
		var i ListCoffeesForSimilarityRow
		if err := rows.Scan(
			&i.ID,
			&i.TastingNotes,
			&i.Process,
			&i.RoastLevel,
			&i.Variety,
			&i.RegionID,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoffeesNeedingBackfill = `-- name: ListCoffeesNeedingBackfill :many
SELECT c.id, c.origin_raw, c.region_raw
FROM coffees c
WHERE c.country_code IS NULL AND c.origin_raw IS NOT NULL AND c.origin_raw != ''
`

type ListCoffeesNeedingBackfillRow struct {
	ID        int64       `json:"id"`
	OriginRaw pgtype.Text `json:"origin_raw"`
	RegionRaw pgtype.Text `json:"region_raw"`
}

func (q *Queries) ListCoffeesNeedingBackfill(ctx context.Context) ([]ListCoffeesNeedingBackfillRow, error) {
	rows, err := q.db.Query(ctx, listCoffeesNeedingBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffeesNeedingBackfillRow{}
	for rows.Next() {
		var i ListCoffeesNeedingBackfillRow
		if err := rows.Scan(&i.ID, &i.OriginRaw, &i.RegionRaw); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoffeesNeedingVariety = `-- name: ListCoffeesNeedingVariety :many
SELECT c.id, c.variety_raw
FROM coffees c
WHERE c.variety_raw IS NOT NULL AND c.variety_raw != '' AND c.variety IS NULL
`

type ListCoffeesNeedingVarietyRow struct {
	ID         int64       `json:"id"`
	VarietyRaw pgtype.Text `json:"variety_raw"`
}

func (q *Queries) ListCoffeesNeedingVariety(ctx context.Context) ([]ListCoffeesNeedingVarietyRow, error) {
	rows, err := q.db.Query(ctx, listCoffeesNeedingVariety)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffeesNeedingVarietyRow{}
	for rows.Next() {
		var i ListCoffeesNeedingVarietyRow
		if err := rows.Scan(&i.ID, &i.VarietyRaw); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctOrigins = `-- name: ListDistinctOrigins :many
SELECT DISTINCT origin_raw
FROM coffees
WHERE origin_raw IS NOT NULL AND origin_raw != ''
ORDER BY origin_raw
`

func (q *Queries) ListDistinctOrigins(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listDistinctOrigins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var origin_raw pgtype.Text
		if err := rows.Scan(&origin_raw); err != nil {
			return nil, err
		}
		items = append(items, origin_raw)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCoffees = `-- name: SearchCoffees :many
SELECT
    c.id, c.roaster_id, c.name, c.product_url, c.image_url,
    c.country_code, c.origin_raw, c.region_raw, c.process, c.roast_level,
    c.tasting_notes, c.price_cents, c.weight_grams, c.in_stock,
    c.variety, c.species,
    c.price_per_100g_min, c.price_per_100g_max, c.is_blend,
    r.name AS roaster_name, r.slug AS roaster_slug,
    co.name AS country_name,
    reg.name AS region_name, reg.id AS coffee_region_id,
    p.name AS producer_name, p.id AS coffee_producer_id
FROM coffees c
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN countries co ON co.code = c.country_code
LEFT JOIN regions reg ON reg.id = c.region_id
LEFT JOIN producers p ON p.id = c.producer_id
WHERE r.opted_out = false
    AND c.in_stock = true
    AND c.search_vector @@ plainto_tsquery('english', $1)
ORDER BY ts_rank(c.search_vector, plainto_tsquery('english', $1)) DESC
LIMIT $2 OFFSET $3
`

type SearchCoffeesParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

type SearchCoffeesRow struct {
	ID               int64       `json:"id"`
	RoasterID        int32       `json:"roaster_id"`
	Name             string      `json:"name"`
	ProductUrl       pgtype.Text `json:"product_url"`
	ImageUrl         pgtype.Text `json:"image_url"`
	CountryCode      pgtype.Text `json:"country_code"`
	OriginRaw        pgtype.Text `json:"origin_raw"`
	RegionRaw        pgtype.Text `json:"region_raw"`
	Process          pgtype.Text `json:"process"`
	RoastLevel       pgtype.Text `json:"roast_level"`
	TastingNotes     []string    `json:"tasting_notes"`
	PriceCents       pgtype.Int4 `json:"price_cents"`
	WeightGrams      pgtype.Int4 `json:"weight_grams"`
	InStock          bool        `json:"in_stock"`
	Variety          pgtype.Text `json:"variety"`
	Species          pgtype.Text `json:"species"`
	PricePer100gMin  pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax  pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend          bool        `json:"is_blend"`
	RoasterName      string      `json:"roaster_name"`
	RoasterSlug      string      `json:"roaster_slug"`
	CountryName      pgtype.Text `json:"country_name"`
	RegionName       pgtype.Text `json:"region_name"`
	CoffeeRegionID   pgtype.Int4 `json:"coffee_region_id"`
	ProducerName     pgtype.Text `json:"producer_name"`
	CoffeeProducerID pgtype.Int4 `json:"coffee_producer_id"`
}

func (q *Queries) SearchCoffees(ctx context.Context, arg SearchCoffeesParams) ([]SearchCoffeesRow, error) {
	rows, err := q.db.Query(ctx, searchCoffees, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCoffeesRow{}
	for rows.Next() {
		var i SearchCoffeesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoasterID,
			&i.Name,
			&i.ProductUrl,
			&i.ImageUrl,
			&i.CountryCode,
			&i.OriginRaw,
			&i.RegionRaw,
			&i.Process,
			&i.RoastLevel,
			&i.TastingNotes,
			&i.PriceCents,
			&i.WeightGrams,
			&i.InStock,
			&i.Variety,
			&i.Species,
			&i.PricePer100gMin,
			&i.PricePer100gMax,
			&i.IsBlend,
			&i.RoasterName,
			&i.RoasterSlug,
			&i.CountryName,
			&i.RegionName,
			&i.CoffeeRegionID,
			&i.ProducerName,
			&i.CoffeeProducerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoffeeOrigin = `-- name: UpdateCoffeeOrigin :exec
UPDATE coffees
SET country_code = $2, region_id = $3
WHERE id = $1
`

type UpdateCoffeeOriginParams struct {
	ID          int64       `json:"id"`
	CountryCode pgtype.Text `json:"country_code"`
	RegionID    pgtype.Int4 `json:"region_id"`
}

func (q *Queries) UpdateCoffeeOrigin(ctx context.Context, arg UpdateCoffeeOriginParams) error {
	_, err := q.db.Exec(ctx, updateCoffeeOrigin, arg.ID, arg.CountryCode, arg.RegionID)
	return err
}

const updateCoffeeVariety = `-- name: UpdateCoffeeVariety :exec
UPDATE coffees
SET variety = $2, species = $3
WHERE id = $1
`

type UpdateCoffeeVarietyParams struct {
	ID      int64       `json:"id"`
	Variety pgtype.Text `json:"variety"`
	Species pgtype.Text `json:"species"`
}

func (q *Queries) UpdateCoffeeVariety(ctx context.Context, arg UpdateCoffeeVarietyParams) error {
	_, err := q.db.Exec(ctx, updateCoffeeVariety, arg.ID, arg.Variety, arg.Species)
	return err
}

const upsertCoffee = `-- name: UpsertCoffee :one
INSERT INTO coffees (
    roaster_id, name, product_url, image_url,
    origin_raw, region_raw, variety_raw, process_raw, roast_raw,
    tasting_notes_raw, price_raw, weight_raw, currency, in_stock,
    process, roast_level, tasting_notes, price_cents, weight_grams,
    country_code, region_id, producer_id, producer_raw,
    variety, species,
    price_per_100g_min, price_per_100g_max, is_blend,
    last_seen_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19,
    $20, $21, $22, $23,
    $24, $25,
    $26, $27, $28,
    now()
)
ON CONFLICT (roaster_id, name) DO UPDATE SET
    product_url = EXCLUDED.product_url,
    image_url = EXCLUDED.image_url,
    origin_raw = EXCLUDED.origin_raw,
    region_raw = EXCLUDED.region_raw,
    variety_raw = EXCLUDED.variety_raw,
    process_raw = EXCLUDED.process_raw,
    roast_raw = EXCLUDED.roast_raw,
    tasting_notes_raw = EXCLUDED.tasting_notes_raw,
    price_raw = EXCLUDED.price_raw,
    weight_raw = EXCLUDED.weight_raw,
    currency = EXCLUDED.currency,
    in_stock = EXCLUDED.in_stock,
    process = EXCLUDED.process,
    roast_level = EXCLUDED.roast_level,
    tasting_notes = EXCLUDED.tasting_notes,
    price_cents = EXCLUDED.price_cents,
    weight_grams = EXCLUDED.weight_grams,
    country_code = EXCLUDED.country_code,
    region_id = EXCLUDED.region_id,
    producer_id = EXCLUDED.producer_id,
    producer_raw = EXCLUDED.producer_raw,
    variety = EXCLUDED.variety,
    species = EXCLUDED.species,
    price_per_100g_min = EXCLUDED.price_per_100g_min,
    price_per_100g_max = EXCLUDED.price_per_100g_max,
    is_blend = EXCLUDED.is_blend,
    last_seen_at = now(),
    last_changed_at = CASE
        WHEN coffees.price_cents IS DISTINCT FROM EXCLUDED.price_cents
            OR coffees.in_stock IS DISTINCT FROM EXCLUDED.in_stock
        THEN now()
        ELSE coffees.last_changed_at
    END,
    updated_at = now()
RETURNING (xmax = 0) AS is_new, id
`

type UpsertCoffeeParams struct {
	RoasterID       int32       `json:"roaster_id"`
	Name            string      `json:"name"`
	ProductUrl      pgtype.Text `json:"product_url"`
	ImageUrl        pgtype.Text `json:"image_url"`
	OriginRaw       pgtype.Text `json:"origin_raw"`
	RegionRaw       pgtype.Text `json:"region_raw"`
	VarietyRaw      pgtype.Text `json:"variety_raw"`
	ProcessRaw      pgtype.Text `json:"process_raw"`
	RoastRaw        pgtype.Text `json:"roast_raw"`
	TastingNotesRaw pgtype.Text `json:"tasting_notes_raw"`
	PriceRaw        pgtype.Text `json:"price_raw"`
	WeightRaw       pgtype.Text `json:"weight_raw"`
	Currency        string      `json:"currency"`
	InStock         bool        `json:"in_stock"`
	Process         pgtype.Text `json:"process"`
	RoastLevel      pgtype.Text `json:"roast_level"`
	TastingNotes    []string    `json:"tasting_notes"`
	PriceCents      pgtype.Int4 `json:"price_cents"`
	WeightGrams     pgtype.Int4 `json:"weight_grams"`
	CountryCode     pgtype.Text `json:"country_code"`
	RegionID        pgtype.Int4 `json:"region_id"`
	ProducerID      pgtype.Int4 `json:"producer_id"`
	ProducerRaw     pgtype.Text `json:"producer_raw"`
	Variety         pgtype.Text `json:"variety"`
	Species         pgtype.Text `json:"species"`
	PricePer100gMin pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend         bool        `json:"is_blend"`
}

type UpsertCoffeeRow struct {
	IsNew bool  `json:"is_new"`
	ID    int64 `json:"id"`
}

// Returns true if the row was newly inserted, false if updated.
func (q *Queries) UpsertCoffee(ctx context.Context, arg UpsertCoffeeParams) (UpsertCoffeeRow, error) {
	row := q.db.QueryRow(ctx, upsertCoffee,
		arg.RoasterID,
		arg.Name,
		arg.ProductUrl,
		arg.ImageUrl,
		arg.OriginRaw,
		arg.RegionRaw,
		arg.VarietyRaw,
		arg.ProcessRaw,
		arg.RoastRaw,
		arg.TastingNotesRaw,
		arg.PriceRaw,
		arg.WeightRaw,
		arg.Currency,
		arg.InStock,
		arg.Process,
		arg.RoastLevel,
		arg.TastingNotes,
		arg.PriceCents,
		arg.WeightGrams,
		arg.CountryCode,
		arg.RegionID,
		arg.ProducerID,
		arg.ProducerRaw,
		arg.Variety,
		arg.Species,
		arg.PricePer100gMin,
		arg.PricePer100gMax,
		arg.IsBlend,
	)
	var i UpsertCoffeeRow
	err := row.Scan(&i.IsNew, &i.ID)
	return i, err
}
