// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: countries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCountryByCode = `-- name: GetCountryByCode :one
SELECT code, name, alpha3
FROM countries
WHERE code = $1
`

func (q *Queries) GetCountryByCode(ctx context.Context, code string) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByCode, code)
	var i Country
	err := row.Scan(&i.Code, &i.Name, &i.Alpha3)
	return i, err
}

const getOrCreateRegion = `-- name: GetOrCreateRegion :one
INSERT INTO regions (country_code, name)
VALUES ($1, $2)
ON CONFLICT (country_code, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type GetOrCreateRegionParams struct {
	CountryCode string `json:"country_code"`
	Name        string `json:"name"`
}

func (q *Queries) GetOrCreateRegion(ctx context.Context, arg GetOrCreateRegionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateRegion, arg.CountryCode, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getRegionByID = `-- name: GetRegionByID :one
SELECT reg.id, reg.country_code, reg.name, co.name AS country_name, reg.latitude, reg.longitude
FROM regions reg
JOIN countries co ON co.code = reg.country_code
WHERE reg.id = $1
`

type GetRegionByIDRow struct {
	ID          int32         `json:"id"`
	CountryCode string        `json:"country_code"`
	Name        string        `json:"name"`
	CountryName string        `json:"country_name"`
	Latitude    pgtype.Float8 `json:"latitude"`
	Longitude   pgtype.Float8 `json:"longitude"`
}

func (q *Queries) GetRegionByID(ctx context.Context, id int32) (GetRegionByIDRow, error) {
	row := q.db.QueryRow(ctx, getRegionByID, id)
	var i GetRegionByIDRow
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.Name,
		&i.CountryName,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const listCountriesWithCoffeeCount = `-- name: ListCountriesWithCoffeeCount :many
SELECT co.code, co.name, count(DISTINCT ac.id)::int AS coffee_count
FROM countries co
JOIN (
    SELECT c.id, c.country_code AS match_code, c.roaster_id
    FROM coffees c
    WHERE c.in_stock = true
    UNION
    SELECT bc_c.id, bc.country_code AS match_code, bc_c.roaster_id
    FROM blend_components bc
    JOIN coffees bc_c ON bc_c.id = bc.coffee_id
        AND bc_c.in_stock = true AND bc_c.is_blend = true
) ac ON ac.match_code = co.code
JOIN roasters r ON r.id = ac.roaster_id AND r.opted_out = false
GROUP BY co.code, co.name
ORDER BY co.name
`

type ListCountriesWithCoffeeCountRow struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	CoffeeCount int32  `json:"coffee_count"`
}

func (q *Queries) ListCountriesWithCoffeeCount(ctx context.Context) ([]ListCountriesWithCoffeeCountRow, error) {
	rows, err := q.db.Query(ctx, listCountriesWithCoffeeCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountriesWithCoffeeCountRow{}
	for rows.Next() {
		var i ListCountriesWithCoffeeCountRow
		if err := rows.Scan(&i.Code, &i.Name, &i.CoffeeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearbyRegions = `-- name: ListNearbyRegions :many
SELECT
    r.id,
    r.name,
    r.country_code,
    c.name AS country_name,
    (6371 * acos(
        cos(radians($1::float8)) * cos(radians(r.latitude)) *
        cos(radians(r.longitude) - radians($2::float8)) +
        sin(radians($1::float8)) * sin(radians(r.latitude))
    ))::int AS distance_km,
    count(cof.id)::int AS coffee_count
FROM regions r
JOIN countries c ON c.code = r.country_code
LEFT JOIN coffees cof ON cof.region_id = r.id
LEFT JOIN roasters ro ON ro.id = cof.roaster_id AND ro.opted_out = false
WHERE r.id != $3
  AND r.latitude IS NOT NULL
  AND r.longitude IS NOT NULL
  AND (6371 * acos(
        cos(radians($1::float8)) * cos(radians(r.latitude)) *
        cos(radians(r.longitude) - radians($2::float8)) +
        sin(radians($1::float8)) * sin(radians(r.latitude))
    )) <= $4::int
GROUP BY r.id, r.name, r.country_code, c.name
ORDER BY distance_km
`

type ListNearbyRegionsParams struct {
	SourceLat       float64 `json:"source_lat"`
	SourceLon       float64 `json:"source_lon"`
	ExcludeRegionID int32   `json:"exclude_region_id"`
	MaxDistanceKm   int32   `json:"max_distance_km"`
}

type ListNearbyRegionsRow struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	CountryCode string `json:"country_code"`
	CountryName string `json:"country_name"`
	DistanceKm  int32  `json:"distance_km"`
	CoffeeCount int32  `json:"coffee_count"`
}

func (q *Queries) ListNearbyRegions(ctx context.Context, arg ListNearbyRegionsParams) ([]ListNearbyRegionsRow, error) {
	rows, err := q.db.Query(ctx, listNearbyRegions,
		arg.SourceLat,
		arg.SourceLon,
		arg.ExcludeRegionID,
		arg.MaxDistanceKm,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNearbyRegionsRow{}
	for rows.Next() {
		var i ListNearbyRegionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CountryCode,
			&i.CountryName,
			&i.DistanceKm,
			&i.CoffeeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegionsByCountry = `-- name: ListRegionsByCountry :many
SELECT reg.id, reg.name, count(c.id)::int AS coffee_count
FROM regions reg
LEFT JOIN coffees c ON c.region_id = reg.id AND c.in_stock = true
LEFT JOIN roasters r ON r.id = c.roaster_id AND r.opted_out = false
WHERE reg.country_code = $1
GROUP BY reg.id, reg.name
ORDER BY reg.name
`

type ListRegionsByCountryRow struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	CoffeeCount int32  `json:"coffee_count"`
}

func (q *Queries) ListRegionsByCountry(ctx context.Context, countryCode string) ([]ListRegionsByCountryRow, error) {
	rows, err := q.db.Query(ctx, listRegionsByCountry, countryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegionsByCountryRow{}
	for rows.Next() {
		var i ListRegionsByCountryRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CoffeeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegionsNeedingGeocode = `-- name: ListRegionsNeedingGeocode :many
SELECT r.id, r.name, c.name AS country_name
FROM regions r
JOIN countries c ON c.code = r.country_code
WHERE r.latitude IS NULL
`

type ListRegionsNeedingGeocodeRow struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	CountryName string `json:"country_name"`
}

func (q *Queries) ListRegionsNeedingGeocode(ctx context.Context) ([]ListRegionsNeedingGeocodeRow, error) {
	rows, err := q.db.Query(ctx, listRegionsNeedingGeocode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegionsNeedingGeocodeRow{}
	for rows.Next() {
		var i ListRegionsNeedingGeocodeRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CountryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegionCoordinates = `-- name: UpdateRegionCoordinates :exec
UPDATE regions SET latitude = $2, longitude = $3 WHERE id = $1
`

type UpdateRegionCoordinatesParams struct {
	ID        int32         `json:"id"`
	Latitude  pgtype.Float8 `json:"latitude"`
	Longitude pgtype.Float8 `json:"longitude"`
}

func (q *Queries) UpdateRegionCoordinates(ctx context.Context, arg UpdateRegionCoordinatesParams) error {
	_, err := q.db.Exec(ctx, updateRegionCoordinates, arg.ID, arg.Latitude, arg.Longitude)
	return err
}
