// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_links.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MagicLink struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO magic_links (email, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, email, token, expires_at, used_at, created_at
`

type CreateMagicLinkParams struct {
	Email     string    `json:"email"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRow(ctx, createMagicLink, arg.Email, arg.Token, arg.ExpiresAt)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMagicLinkByToken = `-- name: GetMagicLinkByToken :one
SELECT id, email, token, expires_at, used_at, created_at FROM magic_links
WHERE token = $1 AND expires_at > now() AND used_at IS NULL
`

func (q *Queries) GetMagicLinkByToken(ctx context.Context, token string) (MagicLink, error) {
	row := q.db.QueryRow(ctx, getMagicLinkByToken, token)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMagicLinkUsed = `-- name: MarkMagicLinkUsed :exec
UPDATE magic_links SET used_at = now()
WHERE token = $1
`

func (q *Queries) MarkMagicLinkUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markMagicLinkUsed, token)
	return err
}

const deleteExpiredMagicLinks = `-- name: DeleteExpiredMagicLinks :exec
DELETE FROM magic_links
WHERE expires_at <= now() OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredMagicLinks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMagicLinks)
	return err
}
