// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BlendComponent struct {
	ID          int32       `json:"id"`
	CoffeeID    int32       `json:"coffee_id"`
	CountryCode pgtype.Text `json:"country_code"`
	RegionID    pgtype.Int4 `json:"region_id"`
	Variety     pgtype.Text `json:"variety"`
	Percentage  pgtype.Int4 `json:"percentage"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Coffee struct {
	ID              int64       `json:"id"`
	RoasterID       int32       `json:"roaster_id"`
	Name            string      `json:"name"`
	ProductUrl      pgtype.Text `json:"product_url"`
	ImageUrl        pgtype.Text `json:"image_url"`
	OriginRaw       pgtype.Text `json:"origin_raw"`
	RegionRaw       pgtype.Text `json:"region_raw"`
	VarietyRaw      pgtype.Text `json:"variety_raw"`
	ProcessRaw      pgtype.Text `json:"process_raw"`
	RoastRaw        pgtype.Text `json:"roast_raw"`
	TastingNotesRaw pgtype.Text `json:"tasting_notes_raw"`
	PriceRaw        pgtype.Text `json:"price_raw"`
	WeightRaw       pgtype.Text `json:"weight_raw"`
	Currency        string      `json:"currency"`
	InStock         bool        `json:"in_stock"`
	Process         pgtype.Text `json:"process"`
	RoastLevel      pgtype.Text `json:"roast_level"`
	TastingNotes    []string    `json:"tasting_notes"`
	PriceCents      pgtype.Int4 `json:"price_cents"`
	WeightGrams     pgtype.Int4 `json:"weight_grams"`
	SearchVector    interface{} `json:"search_vector"`
	FirstSeenAt     time.Time   `json:"first_seen_at"`
	LastSeenAt      time.Time   `json:"last_seen_at"`
	LastChangedAt   time.Time   `json:"last_changed_at"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	CountryCode     pgtype.Text `json:"country_code"`
	RegionID        pgtype.Int4 `json:"region_id"`
	ProducerID      pgtype.Int4 `json:"producer_id"`
	ProducerRaw     pgtype.Text `json:"producer_raw"`
	Variety         pgtype.Text `json:"variety"`
	Species         pgtype.Text `json:"species"`
	PricePer100gMin pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax pgtype.Int4 `json:"price_per_100g_max"`
	IsBlend         bool        `json:"is_blend"`
}

type Country struct {
	Code   string      `json:"code"`
	Name   string      `json:"name"`
	Alpha3 pgtype.Text `json:"alpha3"`
}

type Producer struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	CountryCode pgtype.Text `json:"country_code"`
	RegionID    pgtype.Int4 `json:"region_id"`
}

type Region struct {
	ID          int32         `json:"id"`
	CountryCode string        `json:"country_code"`
	Name        string        `json:"name"`
	Latitude    pgtype.Float8 `json:"latitude"`
	Longitude   pgtype.Float8 `json:"longitude"`
}

type Roaster struct {
	ID          int32       `json:"id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Website     string      `json:"website"`
	State       pgtype.Text `json:"state"`
	Description pgtype.Text `json:"description"`
	OptedOut    bool        `json:"opted_out"`
	Active      bool        `json:"active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type ScrapeRun struct {
	ID             int64              `json:"id"`
	RoasterID      int32              `json:"roaster_id"`
	StartedAt      time.Time          `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Status         string             `json:"status"`
	CoffeesFound   pgtype.Int4        `json:"coffees_found"`
	CoffeesAdded   pgtype.Int4        `json:"coffees_added"`
	CoffeesUpdated pgtype.Int4        `json:"coffees_updated"`
	CoffeesRemoved pgtype.Int4        `json:"coffees_removed"`
	PagesVisited   pgtype.Int4        `json:"pages_visited"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	DurationMs     pgtype.Int4        `json:"duration_ms"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    int32     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int32     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
