// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: producers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrCreateProducer = `-- name: GetOrCreateProducer :one
INSERT INTO producers (name, country_code, region_id)
VALUES ($1, $2, $3)
ON CONFLICT (name, country_code) DO UPDATE SET
    region_id = COALESCE(EXCLUDED.region_id, producers.region_id)
RETURNING id
`

type GetOrCreateProducerParams struct {
	Name        string      `json:"name"`
	CountryCode pgtype.Text `json:"country_code"`
	RegionID    pgtype.Int4 `json:"region_id"`
}

func (q *Queries) GetOrCreateProducer(ctx context.Context, arg GetOrCreateProducerParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateProducer, arg.Name, arg.CountryCode, arg.RegionID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getProducerByID = `-- name: GetProducerByID :one
SELECT p.id, p.name, p.country_code, p.region_id,
       co.name AS country_name,
       reg.name AS region_name
FROM producers p
LEFT JOIN countries co ON co.code = p.country_code
LEFT JOIN regions reg ON reg.id = p.region_id
WHERE p.id = $1
`

type GetProducerByIDRow struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	CountryCode pgtype.Text `json:"country_code"`
	RegionID    pgtype.Int4 `json:"region_id"`
	CountryName pgtype.Text `json:"country_name"`
	RegionName  pgtype.Text `json:"region_name"`
}

func (q *Queries) GetProducerByID(ctx context.Context, id int32) (GetProducerByIDRow, error) {
	row := q.db.QueryRow(ctx, getProducerByID, id)
	var i GetProducerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CountryCode,
		&i.RegionID,
		&i.CountryName,
		&i.RegionName,
	)
	return i, err
}

const listProducersWithCoffeeCount = `-- name: ListProducersWithCoffeeCount :many
SELECT p.id, p.name, p.country_code, co.name AS country_name,
       count(c.id)::int AS coffee_count
FROM producers p
LEFT JOIN countries co ON co.code = p.country_code
JOIN coffees c ON c.producer_id = p.id
JOIN roasters r ON r.id = c.roaster_id
WHERE r.opted_out = false
GROUP BY p.id, p.name, p.country_code, co.name
ORDER BY p.name
`

type ListProducersWithCoffeeCountRow struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	CountryCode pgtype.Text `json:"country_code"`
	CountryName pgtype.Text `json:"country_name"`
	CoffeeCount int32       `json:"coffee_count"`
}

func (q *Queries) ListProducersWithCoffeeCount(ctx context.Context) ([]ListProducersWithCoffeeCountRow, error) {
	rows, err := q.db.Query(ctx, listProducersWithCoffeeCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProducersWithCoffeeCountRow{}
	for rows.Next() {
		var i ListProducersWithCoffeeCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CountryCode,
			&i.CountryName,
			&i.CoffeeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
