// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roasters.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRoasters = `-- name: CountRoasters :one
SELECT count(*) FROM roasters WHERE active = true AND opted_out = false
`

func (q *Queries) CountRoasters(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoasters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRoasterBySlug = `-- name: GetRoasterBySlug :one
SELECT id, slug, name, website, state, logo_url, description, active, created_at, updated_at
FROM roasters
WHERE slug = $1 AND opted_out = false
`

type GetRoasterBySlugRow struct {
	ID          int32       `json:"id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Website     string      `json:"website"`
	State       pgtype.Text `json:"state"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	Description pgtype.Text `json:"description"`
	Active      bool        `json:"active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

func (q *Queries) GetRoasterBySlug(ctx context.Context, slug string) (GetRoasterBySlugRow, error) {
	row := q.db.QueryRow(ctx, getRoasterBySlug, slug)
	var i GetRoasterBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Website,
		&i.State,
		&i.LogoUrl,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoasters = `-- name: ListRoasters :many
SELECT r.id, r.slug, r.name, r.website, r.state, r.logo_url,
    count(c.id)::int AS coffee_count
FROM roasters r
LEFT JOIN coffees c ON c.roaster_id = r.id AND c.in_stock = true
WHERE r.active = true AND r.opted_out = false
GROUP BY r.id, r.slug, r.name, r.website, r.state, r.logo_url
ORDER BY r.name
`

type ListRoastersRow struct {
	ID          int32       `json:"id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Website     string      `json:"website"`
	State       pgtype.Text `json:"state"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	CoffeeCount int32       `json:"coffee_count"`
}

func (q *Queries) ListRoasters(ctx context.Context) ([]ListRoastersRow, error) {
	rows, err := q.db.Query(ctx, listRoasters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoastersRow{}
	for rows.Next() {
		var i ListRoastersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Website,
			&i.State,
			&i.LogoUrl,
			&i.CoffeeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoastersByState = `-- name: ListRoastersByState :many
SELECT r.id, r.slug, r.name, r.website, r.state, r.logo_url,
    count(c.id)::int AS coffee_count
FROM roasters r
LEFT JOIN coffees c ON c.roaster_id = r.id AND c.in_stock = true
WHERE r.state = $1 AND r.active = true AND r.opted_out = false
GROUP BY r.id, r.slug, r.name, r.website, r.state, r.logo_url
ORDER BY r.name
`

type ListRoastersByStateRow struct {
	ID          int32       `json:"id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Website     string      `json:"website"`
	State       pgtype.Text `json:"state"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	CoffeeCount int32       `json:"coffee_count"`
}

func (q *Queries) ListRoastersByState(ctx context.Context, state pgtype.Text) ([]ListRoastersByStateRow, error) {
	rows, err := q.db.Query(ctx, listRoastersByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoastersByStateRow{}
	for rows.Next() {
		var i ListRoastersByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Website,
			&i.State,
			&i.LogoUrl,
			&i.CoffeeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoaster = `-- name: UpsertRoaster :one
INSERT INTO roasters (slug, name, website, state)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    website = EXCLUDED.website,
    state = EXCLUDED.state,
    updated_at = now()
RETURNING id
`

type UpsertRoasterParams struct {
	Slug    string      `json:"slug"`
	Name    string      `json:"name"`
	Website string      `json:"website"`
	State   pgtype.Text `json:"state"`
}

func (q *Queries) UpsertRoaster(ctx context.Context, arg UpsertRoasterParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertRoaster,
		arg.Slug,
		arg.Name,
		arg.Website,
		arg.State,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
