// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scrape_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeScrapeRun = `-- name: CompleteScrapeRun :exec
UPDATE scrape_runs
SET status = $2,
    finished_at = now(),
    coffees_found = $3,
    coffees_added = $4,
    coffees_updated = $5,
    duration_ms = $6
WHERE id = $1
`

type CompleteScrapeRunParams struct {
	ID             int64       `json:"id"`
	Status         string      `json:"status"`
	CoffeesFound   pgtype.Int4 `json:"coffees_found"`
	CoffeesAdded   pgtype.Int4 `json:"coffees_added"`
	CoffeesUpdated pgtype.Int4 `json:"coffees_updated"`
	DurationMs     pgtype.Int4 `json:"duration_ms"`
}

func (q *Queries) CompleteScrapeRun(ctx context.Context, arg CompleteScrapeRunParams) error {
	_, err := q.db.Exec(ctx, completeScrapeRun,
		arg.ID,
		arg.Status,
		arg.CoffeesFound,
		arg.CoffeesAdded,
		arg.CoffeesUpdated,
		arg.DurationMs,
	)
	return err
}

const failScrapeRun = `-- name: FailScrapeRun :exec
UPDATE scrape_runs
SET status = 'failed',
    finished_at = now(),
    error_message = $2,
    duration_ms = $3
WHERE id = $1
`

type FailScrapeRunParams struct {
	ID           int64       `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
	DurationMs   pgtype.Int4 `json:"duration_ms"`
}

func (q *Queries) FailScrapeRun(ctx context.Context, arg FailScrapeRunParams) error {
	_, err := q.db.Exec(ctx, failScrapeRun, arg.ID, arg.ErrorMessage, arg.DurationMs)
	return err
}

const insertScrapeRun = `-- name: InsertScrapeRun :one
INSERT INTO scrape_runs (roaster_id, status)
VALUES ($1, 'running')
RETURNING id
`

func (q *Queries) InsertScrapeRun(ctx context.Context, roasterID int32) (int64, error) {
	row := q.db.QueryRow(ctx, insertScrapeRun, roasterID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listScrapeRunsByRoaster = `-- name: ListScrapeRunsByRoaster :many
SELECT id, roaster_id, started_at, finished_at, status,
       coffees_found, coffees_added, coffees_updated, coffees_removed,
       pages_visited, error_message, duration_ms
FROM scrape_runs
WHERE roaster_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListScrapeRunsByRoasterParams struct {
	RoasterID int32 `json:"roaster_id"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) ListScrapeRunsByRoaster(ctx context.Context, arg ListScrapeRunsByRoasterParams) ([]ScrapeRun, error) {
	rows, err := q.db.Query(ctx, listScrapeRunsByRoaster, arg.RoasterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapeRun{}
	for rows.Next() {
		var i ScrapeRun
		if err := rows.Scan(
			&i.ID,
			&i.RoasterID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.CoffeesFound,
			&i.CoffeesAdded,
			&i.CoffeesUpdated,
			&i.CoffeesRemoved,
			&i.PagesVisited,
			&i.ErrorMessage,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
