// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_tasting_notes.sql

package db

import (
	"context"
	"time"
)

type UserTastingNote struct {
	ID          int32     `json:"id"`
	UserID      int32     `json:"user_id"`
	CoffeeID    int64     `json:"coffee_id"`
	TastingNote string    `json:"tasting_note"`
	CreatedAt   time.Time `json:"created_at"`
}

const addUserTastingNote = `-- name: AddUserTastingNote :one
INSERT INTO user_tasting_notes (user_id, coffee_id, tasting_note)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, coffee_id, tasting_note) DO NOTHING
RETURNING id, user_id, coffee_id, tasting_note, created_at
`

type AddUserTastingNoteParams struct {
	UserID      int32  `json:"user_id"`
	CoffeeID    int64  `json:"coffee_id"`
	TastingNote string `json:"tasting_note"`
}

func (q *Queries) AddUserTastingNote(ctx context.Context, arg AddUserTastingNoteParams) (UserTastingNote, error) {
	row := q.db.QueryRow(ctx, addUserTastingNote, arg.UserID, arg.CoffeeID, arg.TastingNote)
	var i UserTastingNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoffeeID,
		&i.TastingNote,
		&i.CreatedAt,
	)
	return i, err
}

const removeUserTastingNote = `-- name: RemoveUserTastingNote :exec
DELETE FROM user_tasting_notes
WHERE user_id = $1 AND coffee_id = $2 AND tasting_note = $3
`

type RemoveUserTastingNoteParams struct {
	UserID      int32  `json:"user_id"`
	CoffeeID    int64  `json:"coffee_id"`
	TastingNote string `json:"tasting_note"`
}

func (q *Queries) RemoveUserTastingNote(ctx context.Context, arg RemoveUserTastingNoteParams) error {
	_, err := q.db.Exec(ctx, removeUserTastingNote, arg.UserID, arg.CoffeeID, arg.TastingNote)
	return err
}

const listUserTastingNotesForCoffee = `-- name: ListUserTastingNotesForCoffee :many
SELECT tasting_note FROM user_tasting_notes
WHERE user_id = $1 AND coffee_id = $2
`

type ListUserTastingNotesForCoffeeParams struct {
	UserID   int32 `json:"user_id"`
	CoffeeID int64 `json:"coffee_id"`
}

func (q *Queries) ListUserTastingNotesForCoffee(ctx context.Context, arg ListUserTastingNotesForCoffeeParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserTastingNotesForCoffee, arg.UserID, arg.CoffeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tasting_note string
		if err := rows.Scan(&tasting_note); err != nil {
			return nil, err
		}
		items = append(items, tasting_note)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrowdsourcedTastingNotes = `-- name: ListCrowdsourcedTastingNotes :many
SELECT tasting_note, COUNT(*) AS vote_count
FROM user_tasting_notes
WHERE coffee_id = $1
GROUP BY tasting_note
ORDER BY vote_count DESC, tasting_note ASC
`

type ListCrowdsourcedTastingNotesRow struct {
	TastingNote string `json:"tasting_note"`
	VoteCount   int64  `json:"vote_count"`
}

func (q *Queries) ListCrowdsourcedTastingNotes(ctx context.Context, coffeeID int64) ([]ListCrowdsourcedTastingNotesRow, error) {
	rows, err := q.db.Query(ctx, listCrowdsourcedTastingNotes, coffeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCrowdsourcedTastingNotesRow{}
	for rows.Next() {
		var i ListCrowdsourcedTastingNotesRow
		if err := rows.Scan(&i.TastingNote, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
