// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_coffees.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserPasswordless = `-- name: CreateUserPasswordless :one
INSERT INTO users (email, password_hash)
VALUES ($1, '')
RETURNING id, email, password_hash, created_at, updated_at, is_admin
`

func (q *Queries) CreateUserPasswordless(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUserPasswordless, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const deleteUserCoffee = `-- name: DeleteUserCoffee :exec
DELETE FROM user_coffees
WHERE user_id = $1 AND coffee_id = $2
`

type DeleteUserCoffeeParams struct {
	UserID   int32 `json:"user_id"`
	CoffeeID int64 `json:"coffee_id"`
}

func (q *Queries) DeleteUserCoffee(ctx context.Context, arg DeleteUserCoffeeParams) error {
	_, err := q.db.Exec(ctx, deleteUserCoffee, arg.UserID, arg.CoffeeID)
	return err
}

const getUserCoffee = `-- name: GetUserCoffee :one
SELECT id, user_id, coffee_id, status, liked, rating, review, drunk_at, created_at, updated_at FROM user_coffees
WHERE user_id = $1 AND coffee_id = $2
`

type GetUserCoffeeParams struct {
	UserID   int32 `json:"user_id"`
	CoffeeID int64 `json:"coffee_id"`
}

func (q *Queries) GetUserCoffee(ctx context.Context, arg GetUserCoffeeParams) (UserCoffee, error) {
	row := q.db.QueryRow(ctx, getUserCoffee, arg.UserID, arg.CoffeeID)
	var i UserCoffee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoffeeID,
		&i.Status,
		&i.Liked,
		&i.Rating,
		&i.Review,
		&i.DrunkAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserCoffeeIDs = `-- name: ListUserCoffeeIDs :many
SELECT coffee_id, status, liked, rating FROM user_coffees
WHERE user_id = $1
`

type ListUserCoffeeIDsRow struct {
	CoffeeID int64       `json:"coffee_id"`
	Status   string      `json:"status"`
	Liked    pgtype.Bool `json:"liked"`
	Rating   pgtype.Int2 `json:"rating"`
}

func (q *Queries) ListUserCoffeeIDs(ctx context.Context, userID int32) ([]ListUserCoffeeIDsRow, error) {
	rows, err := q.db.Query(ctx, listUserCoffeeIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserCoffeeIDsRow{}
	for rows.Next() {
		var i ListUserCoffeeIDsRow
		if err := rows.Scan(
			&i.CoffeeID,
			&i.Status,
			&i.Liked,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCoffees = `-- name: ListUserCoffees :many
SELECT uc.id, uc.user_id, uc.coffee_id, uc.status, uc.liked, uc.rating, uc.review, uc.drunk_at, uc.created_at, uc.updated_at, c.name AS coffee_name, c.image_url AS coffee_image_url,
       r.name AS roaster_name, r.slug AS roaster_slug, r.logo_url AS roaster_logo_url,
       c.process, c.roast_level, c.tasting_notes, c.variety,
       c.price_cents, c.weight_grams, c.price_per_100g_min, c.price_per_100g_max,
       c.in_stock, c.is_blend, c.is_decaf, c.product_url,
       c.country_code, co.name AS country_name,
       c.region_id, reg.name AS region_name,
       c.species, c.description
FROM user_coffees uc
JOIN coffees c ON c.id = uc.coffee_id
JOIN roasters r ON r.id = c.roaster_id
LEFT JOIN countries co ON co.code = c.country_code
LEFT JOIN regions reg ON reg.id = c.region_id
WHERE uc.user_id = $1
ORDER BY uc.updated_at DESC
`

type ListUserCoffeesRow struct {
	ID              int32       `json:"id"`
	UserID          int32       `json:"user_id"`
	CoffeeID        int64       `json:"coffee_id"`
	Status          string      `json:"status"`
	Liked           pgtype.Bool `json:"liked"`
	Rating          pgtype.Int2 `json:"rating"`
	Review          pgtype.Text `json:"review"`
	DrunkAt         pgtype.Date `json:"drunk_at"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	CoffeeName      string      `json:"coffee_name"`
	CoffeeImageUrl  pgtype.Text `json:"coffee_image_url"`
	RoasterName     string      `json:"roaster_name"`
	RoasterSlug     string      `json:"roaster_slug"`
	RoasterLogoUrl  pgtype.Text `json:"roaster_logo_url"`
	Process         pgtype.Text `json:"process"`
	RoastLevel      pgtype.Text `json:"roast_level"`
	TastingNotes    []string    `json:"tasting_notes"`
	Variety         pgtype.Text `json:"variety"`
	PriceCents      pgtype.Int4 `json:"price_cents"`
	WeightGrams     pgtype.Int4 `json:"weight_grams"`
	PricePer100gMin pgtype.Int4 `json:"price_per_100g_min"`
	PricePer100gMax pgtype.Int4 `json:"price_per_100g_max"`
	InStock         bool        `json:"in_stock"`
	IsBlend         bool        `json:"is_blend"`
	IsDecaf         bool        `json:"is_decaf"`
	ProductUrl      pgtype.Text `json:"product_url"`
	CountryCode     pgtype.Text `json:"country_code"`
	CountryName     pgtype.Text `json:"country_name"`
	RegionID        pgtype.Int4 `json:"region_id"`
	RegionName      pgtype.Text `json:"region_name"`
	Species         pgtype.Text `json:"species"`
	Description     pgtype.Text `json:"description"`
}

func (q *Queries) ListUserCoffees(ctx context.Context, userID int32) ([]ListUserCoffeesRow, error) {
	rows, err := q.db.Query(ctx, listUserCoffees, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserCoffeesRow{}
	for rows.Next() {
		var i ListUserCoffeesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CoffeeID,
			&i.Status,
			&i.Liked,
			&i.Rating,
			&i.Review,
			&i.DrunkAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoffeeName,
			&i.CoffeeImageUrl,
			&i.RoasterName,
			&i.RoasterSlug,
			&i.RoasterLogoUrl,
			&i.Process,
			&i.RoastLevel,
			&i.TastingNotes,
			&i.Variety,
			&i.PriceCents,
			&i.WeightGrams,
			&i.PricePer100gMin,
			&i.PricePer100gMax,
			&i.InStock,
			&i.IsBlend,
			&i.IsDecaf,
			&i.ProductUrl,
			&i.CountryCode,
			&i.CountryName,
			&i.RegionID,
			&i.RegionName,
			&i.Species,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserCoffee = `-- name: UpsertUserCoffee :one
INSERT INTO user_coffees (user_id, coffee_id, status, liked, rating, review, drunk_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, coffee_id)
DO UPDATE SET status = EXCLUDED.status, liked = EXCLUDED.liked, rating = EXCLUDED.rating,
             review = EXCLUDED.review, drunk_at = EXCLUDED.drunk_at, updated_at = now()
RETURNING id, user_id, coffee_id, status, liked, rating, review, drunk_at, created_at, updated_at
`

type UpsertUserCoffeeParams struct {
	UserID   int32       `json:"user_id"`
	CoffeeID int64       `json:"coffee_id"`
	Status   string      `json:"status"`
	Liked    pgtype.Bool `json:"liked"`
	Rating   pgtype.Int2 `json:"rating"`
	Review   pgtype.Text `json:"review"`
	DrunkAt  pgtype.Date `json:"drunk_at"`
}

func (q *Queries) UpsertUserCoffee(ctx context.Context, arg UpsertUserCoffeeParams) (UserCoffee, error) {
	row := q.db.QueryRow(ctx, upsertUserCoffee,
		arg.UserID,
		arg.CoffeeID,
		arg.Status,
		arg.Liked,
		arg.Rating,
		arg.Review,
		arg.DrunkAt,
	)
	var i UserCoffee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoffeeID,
		&i.Status,
		&i.Liked,
		&i.Rating,
		&i.Review,
		&i.DrunkAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
